# Generated by Django 5.2.1 on 2025-05-28 06:15

from django.db import migrations
from datetime import date, timedelta

def set_default_birth_date(apps, schema_editor):
    UserProfile = apps.get_model('profiles', 'UserProfile')
    today = date.today()

    default_birth_date = today - timedelta(days=365*50)

    UserProfile.objects.filter(birth_date__isnull=True).update(birth_date=default_birth_date)


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_birth_date'),
    ]

    operations = [
        migrations.RunPython(set_default_birth_date)
    ]
