# Generated by Django 5.2.1 on 2025-05-28 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_userprofile_email_userprofile_address'),
    ]

    operations = [
    ]
