# Generated by Django 5.2.1 on 2025-05-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('profiles', '0009_userprofile_gender')]
    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120))
            ],
            options={
                'db_table' : 'usersettings'
            }
        ),    
        migrations.AddField(
            model_name='UserProfile',
            name='nickname',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='UserProfile',
            name='user_name',
            field=models.CharField(max_length=150, null=True, blank=True),
        ),
        migrations.RemoveField(
            model_name='UserProfile',
            name='phone',
        ),
    ]