FROM maven:3.8.6-eclipse-temurin-17

WORKDIR /app

COPY pom.xml .
COPY src ./src
COPY testng.xml .
COPY checkstyle.xml .

RUN apt-get update && apt-get install -y google-chrome-stable

CMD ["mvn", "clean", "test", "-Dtestng.xml=testng.xml"]