# Generated by Django 4.2.11 on 2025-05-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codefleet', '0004_alter_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
