# Generated by Django 4.2.20 on 2025-04-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
