# Generated by Django 4.2.20 on 2025-04-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_alter_books_cover_image_alter_books_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=13),
        ),
    ]
