version: '3.8'

services:
  user_service:
    build: ./user_service
    ports:
      - "8000:8000"
    depends_on:
      - user_db
    environment:
      - DJANGO_SETTINGS_MODULE=user_service.settings
      - DATABASE_URL=postgres://user:password@user_db:5432/user_db

  user_db:
    image: postgres:13
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  order_service:
    build: ./order_service
    ports:
      - "8001:8000"
    depends_on:
      - order_db
    environment:
      - DJANGO_SETTINGS_MODULE=order_service.settings
      - DATABASE_URL=postgres://order:password@order_db:5432/order_db
      - USER_SERVICE_URL=http://user_service:8000

  order_db:
    image: postgres:13
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order
      POSTGRES_PASSWORD: password
