services:
  order_service:
    build: ../order_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://order_user:order_pass@order_db:5432/order_db
      - USER_SERVICE_URL=http://user_service:8001
    depends_on:
      - order_db
    networks:
      - ecommerce-network

  order_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=order_user
      - POSTGRES_PASSWORD=order_pass
      - POSTGRES_DB=order_db
    volumes:
      - order_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  user_service:
    build: ./user_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://user_user:user_pass@user_db:5432/user_db
    depends_on:
      - user_db
    networks:
      - ecommerce-network

  user_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user_user
      - POSTGRES_PASSWORD=user_pass
      - POSTGRES_DB=user_db
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  order_data:
  user_data: