services:
  user_service:
    build: ../user_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://user_user:user_pass@user_db:5432/user_db
    depends_on:
      - user_db
    networks:
      - ecommerce-network

  user_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user_user
      - POSTGRES_PASSWORD=user_pass
      - POSTGRES_DB=user_db
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  user_data: