name: BooksLibrary CI

on:
  push:
    branches: [main]
    paths:
      - 'python/django-framework/bookslibrary/**'
  pull_request:
    branches: [main]
    paths:
      - 'python/django-framework/bookslibrary/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: bookslab_db
          POSTGRES_USER: bookslab_user
          POSTGRES_PASSWORD: bookslab_password          
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/django-framework/bookslibrary/requirements.txt

      - name: Run migrations
        run: |
          cd python/django-framework/bookslibrary
          python manage.py migrate
        env:
          POSTGRES_HOST: postgres
          POSTGRES_DB: bookslab_db
          DB_NAME: bookslab_db
          POSTGRES_USER: bookslab_user
          POSTGRES_PASSWORD: bookslab_password
          POSTGRES_PORT: 5432
          DJANGO_SETTINGS_MODULE: bookslab.settings

      - name: Load initial data
        run: |
          cd python/django-framework/bookslibrary
          python manage.py loaddata bookslab/initial_data.json
        env:
          POSTGRES_HOST: postgres
          POSTGRES_DB: bookslab_db
          DB_NAME: bookslab_db
          POSTGRES_USER: bookslab_user
          POSTGRES_PASSWORD: bookslab_password
          POSTGRES_PORT: 5432
          DJANGO_SETTINGS_MODULE: bookslab.settings

      - name: Run tests
        run: |
          cd python/django-framework/bookslibrary
          python manage.py test
        env:
          POSTGRES_HOST: postgres
          POSTGRES_DB: bookslab_db
          DB_NAME: bookslab_db
          POSTGRES_USER: bookslab_user
          POSTGRES_PASSWORD: bookslab_password
          POSTGRES_PORT: 5432
          DJANGO_SETTINGS_MODULE: bookslab.settings

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 python/django-framework/bookslibrary/bookslab --max-line-length=120 --exclude=migrations
