name: BooksLibrary CI

on:
  push:
    branches: [main]
    paths:
      - 'bookslibrary/**'
  pull_request:
    branches: [main]
    paths:
      - 'bookslibrary/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: codefleet_bookslibrary
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bookslibrary/requirements.txt

      - name: Run migrations
        run: |
          cd bookslibrary
          python manage.py migrate
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB: codefleet_bookslibrary
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_PORT: 5432
          DJANGO_SETTINGS_MODULE: settings

      - name: Run tests
        run: |
          cd bookslibrary
          python manage.py test

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 bookslibrary --max-line-length=120 --exclude=migrations