# Deployment workflow for Azure

name: Azure CI

on:
    push:
      branches: [main]
      paths:
        - 'azure/**'
    pull_request:
      branches: [main]
      paths:
        - 'azure/**'
    workflow_dispatch: # Allows manual triggering
  
jobs:
    test-django:
        runs-on: ubuntu-latest