# CI/CD for standalone Java programs

name: Java CI

on:
    push:
      branches: [main]
      paths:
        - 'java/**'
    pull_request:
      branches: [main]
      paths:
        - 'java/**'
    workflow_dispatch: # Allows manual triggering
  
jobs:
    test-django:
        runs-on: ubuntu-latest