name: Sync Develop with Main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync main and develop
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      - name: Authenticate and Sync Branches
        env:
          GH_PAT: ${{ secrets.act-local-token }}
        run: |
          git remote set-url origin https://x-access-token:${act-local-token}@github.com/vbgiyor/codefleet.git
          git fetch origin
          git checkout main
          git pull origin main
          git checkout develop
          git pull origin develop
          git merge origin/main --no-edit
          git push origin develop