name: Sync Develop with Main

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for pushing changes
    steps:
      - uses: actions/checkout@v4 # Updated to v4 for latest features
        with:
          token: ${{ secrets.GH_TOKEN }} # Use PAT or GitHub token from secrets
          fetch-depth: 0 # Full history for accurate merges
      - name: Sync main and develop
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git checkout main
          git pull origin main
          git checkout develop
          git pull origin develop
          git merge main --no-edit
          git push origin develop
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Ensure token is available
