services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codefleet_bookslibrary
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5433:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn wsgi:application --bind 0.0.0.0:8003
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=codefleet_bookslibrary
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
      - DJANGO_SETTINGS_MODULE=settings
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: