services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      USE_DOCKER: "1"
    depends_on:
      - db
    networks:
      - bookslab-network
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=bookslab_user
      - POSTGRES_PASSWORD=bookslab_password
      - POSTGRES_DB=bookslab_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookslab_user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bookslab-network
networks:
  bookslab-network:
    driver: bridge
volumes:
  postgres_data: